// Generated by CoffeeScript 1.8.0
(function() {
  var boardIsFull, buildBoard, collapseCells, generateTile, getColumn, getRow, isGameOver, mergeCells, move, moveIsValid, noValidMoves, printArray, randomCellIndices, randomInt, randomValue, setColumn, setRow, showBoard,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  randomInt = function(x) {
    return Math.floor(Math.random() * x);
  };

  randomCellIndices = function() {
    return [randomInt(4), randomInt(4)];
  };

  randomValue = function() {
    var values;
    values = [2, 2, 2, 4];
    return values[randomInt(4)];
  };

  buildBoard = function() {
    return [0, 1, 2, 3].map((function() {
      return [0, 1, 2, 3].map((function() {
        return 0;
      }));
    }));
  };

  generateTile = function(board) {
    var column, row, value, _ref;
    value = randomValue();
    _ref = randomCellIndices(), row = _ref[0], column = _ref[1];
    console.log("row: " + row + " / col: " + column);
    if (board[row][column] === 0) {
      board[row][column] = value;
    } else {
      console.log('generate infinitely');
      generateTile(board);
    }
    return console.log("generate tile");
  };

  move = function(board, direction) {
    var column, i, newBoard, row, _i;
    newBoard = buildBoard();
    for (i = _i = 0; _i <= 3; i = ++_i) {
      if (direction === 'right' || direction === 'left') {
        row = getRow(i, board);
        row = mergeCells(row, direction);
        row = collapseCells(row, direction);
        setRow(row, i, newBoard);
      } else if (direction === 'up' || direction === 'down') {
        column = getColumn(i, board);
        column = mergeCells(column, direction);
        column = collapseCells(column, direction);
        setColumn(column, i, newBoard);
      }
    }
    return newBoard;
  };

  getRow = function(r, board) {
    return [board[r][0], board[r][1], board[r][2], board[r][3]];
  };

  getColumn = function(c, board) {
    return [board[0][c], board[1][c], board[2][c], board[3][c]];
  };

  setRow = function(row, index, board) {
    return board[index] = row;
  };

  setColumn = function(column, index, board) {
    var i, _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 3; i = ++_i) {
      _results.push(board[i][index] = column[i]);
    }
    return _results;
  };

  mergeCells = function(cells, direction) {
    var merge;
    merge = function(cells) {
      var a, b, _i, _j, _ref;
      for (a = _i = 3; _i > 0; a = --_i) {
        for (b = _j = _ref = a - 1; _ref <= 0 ? _j <= 0 : _j >= 0; b = _ref <= 0 ? ++_j : --_j) {
          if (cells[a] === 0) {
            break;
          } else if (cells[a] === cells[b]) {
            cells[a] *= 2;
            cells[b] = 0;
            $(".steal").trigger("play");
            break;
          } else if (cells[b] !== 0) {
            break;
          }
        }
      }
      return cells;
    };
    if (direction === 'right' || direction === 'down') {
      cells = merge(cells);
    } else if (direction === 'left' || direction === 'up') {
      cells = merge(cells.reverse()).reverse();
    }
    return cells;
  };

  collapseCells = function(cells, direction) {
    cells = cells.filter(function(x) {
      return x !== 0;
    });
    while (cells.length < 4) {
      if (direction === 'right' || direction === 'down') {
        cells.unshift(0);
      } else if (direction === 'left' || direction === 'up') {
        cells.push(0);
      }
    }
    return cells;
  };

  moveIsValid = function(originalBoard, newBoard) {
    var col, row, _i, _j;
    for (row = _i = 0; _i <= 3; row = ++_i) {
      for (col = _j = 0; _j <= 3; col = ++_j) {
        if (originalBoard[row][col] !== newBoard[row][col]) {
          return true;
        }
      }
    }
    return false;
  };

  boardIsFull = function(board) {
    var row, _i, _len;
    for (_i = 0, _len = board.length; _i < _len; _i++) {
      row = board[_i];
      if (__indexOf.call(row, 0) >= 0) {
        return false;
      }
    }
    return true;
  };

  noValidMoves = function(board) {
    var direction, directions, newBoard, _i, _len;
    directions = ['right', 'left', 'up', 'down'];
    for (_i = 0, _len = directions.length; _i < _len; _i++) {
      direction = directions[_i];
      newBoard = move(board, direction);
      if (moveIsValid(board, newBoard)) {
        return false;
      }
    }
    return true;
  };

  isGameOver = function(board) {
    return boardIsFull(board) && noValidMoves(board);
  };

  showBoard = function(board) {
    var col, row, width, _i, _results;
    _results = [];
    for (row = _i = 0; _i <= 3; row = ++_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (col = _j = 0; _j <= 3; col = ++_j) {
          if (board[row][col] === 0) {
            _results1.push($(".r" + row + ".c" + col + " > div").html(''));
          } else {
            width = board[row][col] + 100;
            _results1.push($(".r" + row + ".c" + col + " > div").html("<img src=\"img/nc.jpg\" width=\"" + width + "\">"));
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

  printArray = function(array) {
    var row, _i, _len;
    console.log("-- Start --");
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      console.log(row);
    }
    return console.log("--  End  --");
  };

  $(function() {
    this.board = buildBoard();
    generateTile(this.board);
    generateTile(this.board);
    showBoard(this.board);
    return $('body').keydown((function(_this) {
      return function(e) {
        var direction, key, keys, newBoard;
        key = e.which;
        keys = [37, 38, 39, 40];
        if (__indexOf.call(keys, key) >= 0) {
          e.preventDefault();
          console.log("key: ", key);
          direction = (function() {
            switch (key) {
              case 37:
                return 'left';
              case 38:
                return 'up';
              case 39:
                return 'right';
              case 40:
                return 'down';
            }
          })();
          newBoard = move(_this.board, direction);
          printArray(_this.board);
          printArray(newBoard);
          if (moveIsValid(_this.board, newBoard)) {
            console.log("valid");
            _this.board = newBoard;
            generateTile(newBoard);
            showBoard(_this.board);
            if (isGameOver(_this.board)) {
              return alert("YOU LOSE!");
            }
          } else {
            return console.log("invalid");
          }
        } else {

        }
      };
    })(this));
  });

}).call(this);

//# sourceMappingURL=main.js.map
