// Generated by CoffeeScript 1.8.0
(function() {
  ({
    "version": 3,
    "file": "main.js",
    "sourceRoot": "..",
    "sources": ["js/main.js"],
    "names": [],
    "mappings": ";AAAA;AAAA;AAAA"
  });

}).call(this);

//# sourceMappingURL=main.js.js.map
