// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard, generateTile, printArray;

  buildBoard = function() {
    return [0, 1, 2, 3].map((function() {
      return [0, 1, 2, 3].map((function() {
        return 0;
      }));
    }));
  };

  generateTile = function() {
    return console.log("generate tile");
  };

  printArray = function(array) {
    var row, _i, _len;
    console.log("-- Start --");
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      console.log(row);
    }
    return console.log("--  End  --");
  };

  $(function() {
    var newBoard;
    newBoard = buildBoard();
    printArray(newBoard);
    generateTile();
    return generateTile();
  });

}).call(this);

//# sourceMappingURL=main.js.map
